version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: medical_postgres
    environment:
      POSTGRES_DB: medical_dw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
